### ISSUE TITLE
Remove references to Slack from CONTRIBUTING.md

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-WordPress-Theme#81]
The project's CONTRIBUTING.md file needs to be updated to replace references and links to the ucf-wp Slack with the UCFTeam-CAMPUS-Wordpress Team.

See https://github.com/UCF/CM-WP-Theme-Template/blob/master/CONTRIBUTING.md as a reference for necessary updates.

**Comment by jmbarne3** [comment]
Resolved in #82
